name: "Deploy: PROD"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Checkout
        uses: actions/checkout@v3
# TODO
