name: 'Deploy: STAGE'

on:
  workflow_dispatch:
  push:
    branches: [stage]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: STAGE

    steps:
      - name: Checkout
        uses: actions/checkout@v2
# TODO
        