name: 'Deploy: PRO'

on:
  workflow_dispatch:
  push:
    branches: [main]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: PRO

    steps:
      - name: Checkout
        uses: actions/checkout@v2
# TODO
        