name: 'Deploy: DEV'

on:
  workflow_dispatch:
  push:
    branches: [dev]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout
        uses: actions/checkout@v2
# TODO
        