name: Run tests on Pull Request

on:
  pull_request:
    branches: [dev]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
# TODO