name: Run tests on Pull Request

on:
  pull_request:
    branches: [dev]
    paths:
      - "packages/server-api/**"

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: check cache
        run: npm run check-cache

      - name: Install dependencies
        run: npm run install:ci

      - name: lint
        run: yarn workspace server-api lint

      - name: build
        run: yarn workspace server-api build

      # - name: test
      #   run: yarn workspace server-api test
