name: PR main - automerge
on:
  pull_request:
    branches: [main]
    types: [labeled, synchronize, opened, reopened]
  check_suite:
    types: [completed]
  status:
    types: [success]
jobs:
  automerge:
    if: ${{ github.event.label.name == 'automerge' }} && github.event.check_suite.conclusion == 'success' || github.event.status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_DELETE_BRANCH: "true"
