version: "3"

services:
  hello-world:
    container_name: hello-world
    image: hello-world:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9000:8080
